# Generated by Django 4.1.13 on 2024-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_remove_pregunta_es_opcion_multiple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
    ]
